[suse]
image=registry.opensuse.org/opensuse/tumbleweed:latest
start_now=true
replace=true
pull=true
hostname=suse
# Enable Sigapore repositores
#pre_init_hooks=zypper ar http://download.nus.edu.sg/mirror/opensuse/tumbleweed/repo/oss/ sg-repo-oss;
#pre_init_hooks=zypper ar http://download.nus.edu.sg/mirror/opensuse/tumbleweed/repo/non-oss/ sg-repo-non-oss;
#pre_init_hooks=zypper mr -p 1 sg-repo-oss;
#pre_init_hooks=zypper mr -p 1 sg-repo-non-oss;
#pre_init_hooks=zypper ref;
# Install packages
additional_packages="git make neovim stow tree yt-dlp"
# Enable vscode repository
init_hooks=sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc;
init_hooks=echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/zypp/repos.d/vscode.repo > /dev/null;
init_hooks=sudo zypper ref;
# Download and install vscode .rpm
init_hooks=curl -L "https://go.microsoft.com/fwlink/?LinkID=760867" --output vscode.rpm;
init_hooks=sudo zypper in -y vscode.rpm;
# Export
exported_bins_path="/home/tie/.local/bin"
exported_bins="/usr/bin/code /usr/bin/git /usr/bin/nvim /usr/bin/stow /usr/bin/tree /usr/bin/yt-dlp"
exported_apps="code"
